<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInitd4e0679c57019ad4f73ecb3ba581bb5c
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('FakerPress\ThirdParty\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \FakerPress\ThirdParty\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInitd4e0679c57019ad4f73ecb3ba581bb5c', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \FakerPress\ThirdParty\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInitd4e0679c57019ad4f73ecb3ba581bb5c', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\FakerPress\ThirdParty\Composer\Autoload\ComposerStaticInitd4e0679c57019ad4f73ecb3ba581bb5c::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        $filesToLoad = \FakerPress\ThirdParty\Composer\Autoload\ComposerStaticInitd4e0679c57019ad4f73ecb3ba581bb5c::$files;
        $requireFile = \Closure::bind(static function ($fileIdentifier, $file) {
            if (empty($GLOBALS['__composer_autoload_files'][$fileIdentifier])) {
                $GLOBALS['__composer_autoload_files'][$fileIdentifier] = true;

                require $file;
            }
        }, null, null);
        foreach ($filesToLoad as $fileIdentifier => $file) {
            $requireFile($fileIdentifier, $file);
        }

        return $loader;
    }
}
